---
title: "BRM5012 R practical"
output: 
    html_document:
        theme: cerulean
        css: style.css
---

This practical workshop will consist of a generic introduction to using the R language for data science followed by an introduction to the [Bioconductor project](https://www.bioconductor.org/), which provides packages useful for bioinformatics.

During the workshop we will be using R on a server we run. However R is free, and you can install it on your own computer. There are two things to download and install:

* [Download R](https://cran.rstudio.com/)
* [Download RStudio](https://www.rstudio.com/products/rstudio/download/)

(R is the language itself. RStudio provides a convenient environment in which to use R.)


## Course material

* [Introduction to R slideshow](slides/slides.pdf)

* [Introduction to R workshop material](https://monashdatafluency.github.io/r-intro-2/)

* [Introduction to Bioconductor slideshow](slides/bioconductor_slides.pdf)

* [Introduction to Bioconductor workshop material](topics/bioconductor.html)


## Files

On the day, these files will already be on the server we are using. Download them here to work with them elsewhere.

* [BRM5012-files.zip](BRM5012-files.zip)

## Further reading

This book fills in further details about using Tidyverse packages:

* ["R for Data Science" by Garrett Grolemund and Hadley Wickham](http://r4ds.had.co.nz/)

Bioconductor is a moving target, so books you find may be out of date. We recommend reading vignettes of relevant packages. Various workshop materials and publications are available to provide an overview.

* [Bioconductor](https://bioconductor.org/)

* [Some further pointers](https://monashdatafluency.github.io/r-intro-2/next-steps.html)

<br>

[Source code on GitHub](https://github.com/MonashBioinformaticsPlatform/2018-BRM5012-R)